CFLAGS = -Wall

converter:
	gcc $(CFLAGS) converter.c -o converter.o
	./converter.o
caches:
	gcc $(CFLAGS) caches.c -o caches.o
	./caches.o
limits:
	gcc $(CFLAGS) limits.c -o limits.o
	./limits.o
pipelining:
	gcc $(CFLAGS) pipelining.c -o pipelining.o
	./pipelining.o
show_bytes:
	gcc $(CFLAGS) show_bytes.c -o show_bytes.o
	./show_bytes.o
assembly:
	gcc $(CFLAGS) assembly.c -o assembly.o
	./assembly.o
